### ISSUE TITLE
tekst valt weg in de nav

### ISSUE THREAD

**Issue by r20222** [yujing-student/look-and-feel-corporate-identity#7]
![image](https://github.com/yujing-student/look-and-feel-corporate-identity/assets/101579892/2adf6a0a-f553-46d8-bcb7-a697b15811b2)

De overzicht en abbonementen en diensten en producten vallen een beetje weg, misschien is het handig om de woorden onder elkaar te zetten?

**Comment by yujing-student** [comment]
<img width="141" alt="image" src="https://github.com/yujing-student/look-and-feel-corporate-identity/assets/100352887/f860b473-168c-418d-932d-9f7ece319430">
navbar is breder gemaakt 

https://github.com/yujing-student/look-and-feel-corporate-identity/blob/4056fc2c93da78487dd5d8025b7d15504e8a30b8/styles/styles.css#L105-L114
