### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by r20222** [yujing-student/look-and-feel-corporate-identity#8]
![image](https://github.com/yujing-student/look-and-feel-corporate-identity/assets/101579892/40417340-4b02-4a13-8caa-890260636977)

Misschien is het leuk om hier nog een favicon toe te voegen? 😎

**Comment by yujing-student** [comment]
<img width="166" alt="image" src="https://github.com/yujing-student/look-and-feel-corporate-identity/assets/100352887/5b3c3ef7-c5cc-4078-86d6-3360d9d80759">
favicon is toegevoegd
