### ISSUE TITLE
details & summary

### ISSUE THREAD

**Issue by r20222** [yujing-student/look-and-feel-corporate-identity#9]
https://github.com/yujing-student/look-and-feel-corporate-identity/blob/353f44b8ec62d0b17035a5c43afe8ff089989893/index.html#L163-L166

Goed gebruik gemaakt van de details & summary tags! 💯 

Misschien is het handig om de tekst `openstaande bedragen zijn via ideal te zien `  nog in  `<p>` tags te zetten.

**Comment by yujing-student** [comment]
https://github.com/yujing-student/look-and-feel-corporate-identity/blob/04c567236fa37783b1a1ef9836c414975a399478/index.html#L166-L191

de <p> is toegevoegd en de tekst staat erin
